# for local development
version: '3.7'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: 'develop-stage'
        ports:
            - '${API_SERVER_PORT}:${API_SERVER_PORT}'
            - '${WEB_DEV_SERVER_PORT}:${WEB_DEV_SERVER_PORT}'
        volumes:
            - '.:/app'
            - '/app/node_modules/'
        command: ["npm", "run", "start"]
        environment:
            - CHOKIDAR_USEPOLLING=true
